services:

  base-datos:
    image: mariadb:11.8.8-noble
    environment:
      - MARIADB_DATABASE=inventario
      - MARIADB_USER=softtek
      - MARIADB_PASSWORD=contrasenia
      - MARIADB_RANDOM_ROOT_PASSWORD=1
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
     - 3306:3306
      

  keycloak:
    image: keycloak/keycloak:26.6.3
    command: start-dev
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin

      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false

      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080

      KC_DB: mariadb
      KC_DB_URL_HOST: base-datos
      KC_DB_URL_PORT: 3306
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: contrasenia

    depends_on:
      base-datos:
        condition: service_healthy

    ports:
      - 7080:8080
      # - 9000:9000 # NOT needed for internal healthcheck
    healthcheck:
      test: ["CMD-SHELL", "curl --head -fsS http://localhost:9000/health/ready | echo $?"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    

