services:

  base-datos:
    image: mariadb:11.8.8-noble
    environment:
      - MARIADB_DATABASE=inventario
      - MARIADB_USER=softtek
      - MARIADB_PASSWORD=contraseña
      - MARIADB_RANDOM_ROOT_PASSWORD=1
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
     - 3306:3306
      

  keycloak:
    image: keycloak/keycloak:26.6.3
    command: start-dev
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin

    
