
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:7080/realms/softtek
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:7080/realms/softtek/protocol/openid-connect/certs
