spring.application.name=backend

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:7080/realms/softtek
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:7080/realms/softtek/protocol/openid-connect/certs

spring.datasource.url=jdbc:mariadb://localhost:3306/inventario
spring.datasource.username=softtek
spring.datasource.password=contrasenia
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect


spring.jpa.show-sql=true